// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_Fiap.Web.AspNet.Persistence;

namespace _05_Fiap.Web.AspNet.Migrations
{
    [DbContext(typeof(CondominioContext))]
    [Migration("20190909115839_BancoCondominioInicio")]
    partial class BancoCondominioInicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_05_Fiap.Web.AspNet.Models.Condomino", b =>
                {
                    b.Property<int>("CondominioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Ativo")
                        .HasColumnName("Ds_Ativo");

                    b.Property<int>("Blocos")
                        .HasColumnName("Qtd_Blocos");

                    b.Property<string>("Nome")
                        .HasColumnName("Nm_Condominio");

                    b.Property<int>("Tipo")
                        .HasColumnName("Ds_Tipo");

                    b.HasKey("CondominioId");

                    b.ToTable("T_Condominio");
                });
#pragma warning restore 612, 618
        }
    }
}
